# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='migra',
    version='1.0',
    description='Like `diff` but for PostgreSQL schemas',
    project_urls={
        "homepage": "https://migra.djrobstep.com/",
        "repository": "https://github.com/djrobstep/migra"
    },
    author='Robert Lechte',
    author_email='robertlechte@gmail.com',
    license='Unlicense',
    entry_points={"console_scripts": ["migra = migra:do_command"]},
    packages=['migra'],
    package_dir={"": "."},
    package_data={},
    install_requires=['schemainspect>=0.1.1552209928', 'six', 'sqlbag'],
    extras_require={
        "dev": [
            "black>=18.9b0; python_version > \"3.6\"", "flake8", "isort",
            "pytest", "pytest-cov", "pytest-sugar"
        ],
        "pg": ["psycopg2-binary"]
    },
)
